### ISSUE TITLE
getdownloadlink

### ISSUE THREAD

**Issue by Pacifierjr** [vic-blt/uptobox-api#1]
getdownloadlink need premium user token?
if need. it is possible to banned my uptobox account? by using this to generate download link?

**Comment by vic-blt** [comment]
Hi, you can generate a download link without being premium.
However regular members have to wait some time before getting the download link (Uptobox's restriction).
Your Uptobox account won't be ban because this library uses their public API (see docs.uptobox.com).
But you can be banned if you generate a download link and then share it to a lot of people.

**Comment by Pacifierjr** [comment]
i see thanks for the info.
by the way i using php code to generate direct download.
and i heard on someone that can prevent banning the account if using create cache on php result? and delete the cache every 3hrs. but i can't find the php code that can create cache result.

may i know if can prevent from banned if you cache result on api php script?

**Comment by vic-blt** [comment]
Caching will only reduce the number of requests but won't prevent you from being banned.
Because the download link (also called hotlink) is generated using your account.
And by sharing the hotlink with everyone, you are violating the [Terms of service](https://uptobox.com/tos).
>  **Account sharing policy**
Each user account must have a personal use and cannot be shared, sharing in the same family circle (under the same roof) is tolerated within the limit where no abuse is found.
In the event of abuse found, we reserve the right to disable access to the account without notice, and to restore access to it in our sole discretion. 

See also on [docs.uptobox.com](https://docs.uptobox.com/#generate-a-download-link) :
> WARNING — Don't use API to generate link and share it to everyone or your account will be banned. It's only for own usage or a plugin where each user will register it's own token.

**Comment by Pacifierjr** [comment]
nice thank you for very helpful information :)
